name: Update RSS Feed
on:
  schedule:
    - cron: '0 */12 * * *'  # 每天UTC 0点和12点运行（北京时间8:00和20:00）<button class="citation-flag" data-index="10">
  workflow_dispatch:        # 允许手动触发 <button class="citation-flag" data-index="5"><button class="citation-flag" data-index="8">

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - uses: actions/checkout@v4

      # 2. 设置Python环境
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. 安装依赖
      - run: pip install requests beautifulsoup4 lxml

      # 4. 生成RSS源列表文件（直接写入你的播主链接）
      - run: |
          echo "https://www.ximalaya.com/album/36264240.xml
          https://www.ximalaya.com/album/5411224.xml
          https://www.ximalaya.com/album/4156778.xml" > rss_sources.txt

      # 5. 执行Python脚本提取音频链接（已修复语法错误）
      - run: |
          python -c "
          import requests
          from bs4 import BeautifulSoup

          with open('rss_sources.txt', 'r') as f:
              rss_list = [url.strip() for url in f if url.strip()]

          with open('rss.txt', 'w', encoding='utf-8') as f:
              for rss in rss_list:
                  try:
                      headers = {'User-Agent': 'Mozilla/5.0', 'Referer': 'https://www.ximalaya.com/'}
                      response = requests.get(rss, headers=headers, timeout=10)
                      soup = BeautifulSoup(response.content, 'xml')
                      for item in soup.find_all('item'):
                          title = item.title.text.strip().replace(' ', '_')
                          enclosure = item.find('enclosure')
                          if enclosure and enclosure.get('url', '').endswith('.m4a'):
                              # 修复点：使用双引号包裹 f-string，避免单引号冲突 <button class="citation-flag" data-index="2"><button class="citation-flag" data-index="4">
                              f.write(f\"{title}&&{enclosure['url']}\\n\")
                  except Exception as e:
                      print(f'Error: {str(e)}')"

      # 6. 提交生成的rss.txt到仓库
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git add rss.txt
          git commit -m "Update RSS $(date +'%Y-%m-%d %H:%M')" || echo "No changes"
          git push
